version: '3.8'
services:
   mongodb:
     image: mongo
     command: mongod --port 27000
     restart: always
     ports:
      - "27000:27000"
     environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
     volumes:
      - ./db:/var/lib/mongodb/data
   redis:
     image: redis
     ports:
      - "6379:6379" 
  #  postgres:
  #    image: postgres
  #    environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=tutorTree
  #     - DATABASE_HOST=postgres
  #    ports:
  #     - "5433:5432"
  #    volumes:
  #     - ./db:/var/lib/postgresql/data

   